name: Deploy website to S3

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@main
        with:
          ref: main
      - uses: actions/setup-node@v3.6.0
        name: Install node
        with:
          node-version: '14.x'
      - name: Build dependencies
        run: yarn install --production
      - name: Build production bundle
        env:
          # GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}
          CI: true
        run: yarn run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Push to S3
        run: yarn run deploy
        env:
          DOMAIN_NAME: recipes.lucaskjaerozhang.com # Probably doesn't do anything
