name: Deploy website to S3

on:
  pull_request_target:
    types: [closed]
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@v2.5.1
        name: Install node
        with:
          node-version: '14.x'
      - name: Build dependencies
        run: npm ci --only=production
      - name: Build production bundle
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}
          CI: true
        run: npm run build
      - uses: actions/upload-artifact@master
        name: Upload website content
        with:
          name: gatsby-public
          path: public
  
  deploy: 
    name: Deploy to S3
    needs: [build-resume, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        name: Download website content
        with:
          name: gatsby-public
          path: public
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Push to S3
        run: aws s3 sync public s3://${{ secrets.AWS_S3_BUCKET }}/ --no-progress --delete
      - name: Invalidate Cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id EWJC89C0ACD7D --paths /index.html /*
