name: "Security scan"

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  code-security:
    name: Code security scan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1