name: PR Check - Code

on: [pull_request]

jobs:
  build-frontend:
    name: Test that frontend production bundle builds
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3.5.1
        name: Install node
        with:
          node-version: '14.x'
      - name: Build dependencies
        run: yarn install --production
      - name: Build production bundle
        env:
          CI: true
        run: yarn run build
      - uses: actions/upload-artifact@main
        name: Upload website content
        with:
          name: gatsby-public
          path: public
  
  test:
    name: Lint and test frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3.5.1
        name: Install node
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install
      # - name: End to end test
      #   run: yarn test
      # - name: Lint
      #   run: yarn run lint
  
  code-security:
    name: Code security scan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1