name: PR Check - Code

on: [pull_request]

jobs:
  links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check links
        run: python link_checker.py
  
  build-frontend:
    name: Test that frontend production bundle builds
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.5.1
        name: Install node
        with:
          node-version: '12.x'
      - name: Build dependencies
        run: npm ci --only=production
      - name: Build production bundle
        env:
          CI: true
        run: npm run build
      - uses: actions/upload-artifact@master
        name: Upload website content
        with:
          name: gatsby-public
          path: public
  
  test:
    name: Lint and test frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.5.1
        name: Install node
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: npm install
      - name: End to end test
        run: npm test
      - name: Lint
        run: npm run lint
  
  code-security:
    name: Code security scan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1